micronaut:
  application:
    name: feed_mic
  test:
    resources:
      enabled: true
  io:
    scan:
      packages:
        - com.riveo
        - repository
netty:
  default:
    allocator:
      max-order: 3
mongodb:
  uri: mongodb://localhost:27017/riveo